// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: "includes 'mocha-lcov-reporter'",
      i: [],
      e: 'node_modules/mocha-lcov-reporter/index.js'
    });
  };

}).call(this);
